stages:
  - name: prepareModelData
    transformations:
      - checkoutCentralModel
      - checkoutProjectDeviantModel
      - alignModelData
      - computeChangeSet
  - name: testAndAssess
    transformations:
      - testAndAssessCheckout
  - name: evolve
    transformations:
      - mergeModels


transformations:
  - name: checkoutCentralModel
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/centralEaRepository
      branch: master

  - name: checkoutProjectDeviantModel
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/projectEaRepository
      branch: master

  - name: alignModelData
    service: ea-model-evolution-service
    command: alignModelData
    parameters:
      projectDeviantArtifactId: "@projectDeviant"
      threshold: "2"
    dependsOn:
      - alias: projectDeviant
        ref: p://this/transformations/checkoutProjectDeviantModel/workspace

  - name: computeChangeSet
    service: ea-model-evolution-service
    command: computeChangeSet
    parameters:
      centralModel: "@central"
      alignedModel: "@aligned"
    dependsOn:
      - alias: central
        ref: p://this/transformations/checkoutCentralModel/workspace
      - alias: aligned
        ref: p://this/transformations/alignModelData/alignModelArtifactId

  - name: testAndAssessCheckout
    service: ea-model-evolution-service
    command: testAndAssessCheckout
    parameters:
      changeSet: "@changeSet"
    dependsOn:
      - alias: changeSet
        ref: p://this/assessments/artifactVerification/changeSet

  - name: mergeModels
    service: ea-model-evolution-service
    command: mergeModels
    parameters:
      centralModel: "@centralModel"
      changeSet: "@changeSet"
    dependsOn:
      - alias: central
        ref: p://this/transformations/checkoutCentralModel/workspace
      - alias: changeSet
        ref: p://this/assessments/artifactVerification/changeSet

assessments:
  - name: artifactVerification
    service: ea-model-evolution-service
    command: artifactVerificationAssessment
    parameters:
      alignedModel: "@alignedModel"
      centralModel: "@centralModel"
      changeSet: "@changeSet"
    dependsOn:
      - alias: alignedModel
        ref: p://this/transformations/alignModelData/alignModelArtifactId
      - alias: centralModel
        ref: p://this/transformations/checkoutCentralModel/workspace
      - alias: changeSet
        ref: p://this/transformations/computeChangeSet/changeSetArtifactId

  - name: syntaxCheckAssessment
    service: ea-model-evolution-service
    command: syntaxCheckAssessment
    parameters:
      checkedModel: "@changeSet"
      repoWithSchemaFile: "@projectModel"
    dependsOn:
      - alias: changeSet
        ref: p://this/transformations/testAndAssessCheckout/changeSetArtifactId
      - alias: projectModel
        ref: p://this/transformations/checkoutProjectDeviantModel/workspace

  - name: mergedSyntaxCheckAssessment
    service: ea-model-evolution-service
    command: syntaxCheckAssessment
    parameters:
      checkedModel: "@mergedModel"
      repoWithSchemaFile: "@projectModel"
    dependsOn:
      - alias: mergedModel
        ref: p://this/transformations/mergeModels/mergedModel
      - alias: projectModel
        ref: p://this/transformations/checkoutProjectDeviantModel/workspace

  - name: consistencyCheckAssessment
    service: ea-model-evolution-service
    command: consistencyCheckAssessment
    parameters:
      checkedModel: "@changeSet"
    dependsOn:
      - alias: changeSet
        ref: p://this/transformations/testAndAssessCheckout/changeSetArtifactId

  - name: mergedConsistencyCheckAssessment
    service: ea-model-evolution-service
    command: consistencyCheckAssessment
    parameters:
      checkedModel: "@mergedModel"
    dependsOn:
      - alias: mergedModel
        ref: p://this/transformations/mergeModels/mergedModel

  - name: calculateKpis
    service: ea-model-evolution-service
    command: eamKpiCalculationAssessment
    parameters:
      checkedModel: "@changeSet"
      metricProperty:
        language: ArchiMate
        languageVersion: 3.0
        metrics:
          - name: Application Continuity Plan
            isCritical: true
            calculate:
              operator: devide
              values:
                - type: simple
                  value: value1
                - type: simple
                  value: value2
              valueDefinitions:
                - id: value1
                  selector:
                    id: CRITICAL_APPLICATION
                    is: Element
                    ofType: Business Process
                    where:
                      queryType: statement
                      query: $CRITICAL_APPLICATION has relation $RELATION to $CRITICALITY_RATING
                      params:
                        - id: CRITICALITY_RATING
                          is: Element
                          ofType: Business Object
                          where:
                            queryType: or
                            queries:
                              - queryType: statement
                                query: $CRITICALITY_RATING has property with name "Criticality Rating" and value "1"
                              - queryType: statement
                                query: $CRITICALITY_RATING has name "Criticality Rating"
                        - id: RELATION
                          is: Relationship
                          ofType: Association
                - id: value2
                  selector:
                    id: ALL_APPLICATIONS
                    is: Element
                    ofType: Business Process
            interpret:
              measure: "%"
              good:
                - value: "0.8"
                  relation: ">="
              normal:
                - relation: ">="
                  value: "0.6"
                - relation: "<"
                  value: "0.8"
              bad:
                - relation: "<"
                  value: "0.6"

          - name: Service portfolio methodology analysis
            description: The number of services analyzed by service portfolio methodology devided by the total number of services.
            calculate:
              operator: devide
              values:
                - type: simple
                  value: value1
                - type: simple
                  value: value2
              valueDefinitions:
                - id: value1
                  selector:
                    id: ANALYZED_BY_SERVICE_PORTFOLIO_METHODOLOGY
                    is: Element
                    ofType: Application Service
                    where:
                      queryType: statement
                      query: $SERVICE_PORTFOLIO_METHODOLOGY has relation $RELATION to $ANALYZED_BY_SERVICE_PORTFOLIO_METHODOLOGY
                      params:
                        - id: RELATION
                          is: Relationship
                          ofType: Association
                          where:
                              queryType: statement
                              query: $RELATION has property with name "analyses" and value "true"
                        - id: SERVICE_PORTFOLIO_METHODOLOGY
                          is: Element
                          ofType: Business Object
                          where:
                            queryType: statement
                            query: $SERVICE_PORTFOLIO_METHODOLOGY has name "Service Portfolio Methodology"
                - id: value2
                  selector:
                    id: ALL_APPLICATION_SERVICES
                    is: Element
                    ofType: Application Service
            interpret:
              measure: "%"
              good:
                - value: "0.8"
                  relation: ">="
              normal:
                - relation: ">="
                  value: "0.6"
                - relation: "<"
                  value: "0.8"
              bad:
                - relation: "<"
                  value: "0.6"
    dependsOn:
      - alias: changeSet
        ref: p://this/transformations/testAndAssessCheckout/changeSetArtifactId

  - name: mergedCalculateKpis
    service: ea-model-evolution-service
    command: eamKpiCalculationAssessment
    parameters:
      checkedModel: "@mergedModel"
      metricProperty:
        language: ArchiMate
        languageVersion: 3.0
        metrics:
          - name: Application Continuity Plan
            isCritical: true
            calculate:
              operator: devide
              values:
                - type: simple
                  value: value1
                - type: simple
                  value: value2
              valueDefinitions:
                - id: value1
                  selector:
                    id: CRITICAL_APPLICATION
                    is: Element
                    ofType: Business Process
                    where:
                      queryType: statement
                      query: $CRITICAL_APPLICATION has relation $RELATION to $CRITICALITY_RATING
                      params:
                        - id: CRITICALITY_RATING
                          is: Element
                          ofType: Business Object
                          where:
                            queryType: or
                            queries:
                              - queryType: statement
                                query: $CRITICALITY_RATING has property with name "Criticality Rating" and value "1"
                              - queryType: statement
                                query: $CRITICALITY_RATING has name "Criticality Rating"
                        - id: RELATION
                          is: Relationship
                          ofType: Association
                - id: value2
                  selector:
                    id: ALL_APPLICATIONS
                    is: Element
                    ofType: Business Process
            interpret:
              measure: "%"
              good:
                - value: "0.8"
                  relation: ">="
              normal:
                - relation: ">="
                  value: "0.6"
                - relation: "<"
                  value: "0.8"
              bad:
                - relation: "<"
                  value: "0.6"

          - name: Service portfolio methodology analysis
            description: The number of services analyzed by service portfolio methodology devided by the total number of services.
            calculate:
              operator: devide
              values:
                - type: simple
                  value: value1
                - type: simple
                  value: value2
              valueDefinitions:
                - id: value1
                  selector:
                    id: ANALYZED_BY_SERVICE_PORTFOLIO_METHODOLOGY
                    is: Element
                    ofType: Application Service
                    where:
                      queryType: statement
                      query: $SERVICE_PORTFOLIO_METHODOLOGY has relation $RELATION to $ANALYZED_BY_SERVICE_PORTFOLIO_METHODOLOGY
                      params:
                        - id: RELATION
                          is: Relationship
                          ofType: Association
                          where:
                              queryType: statement
                              query: $RELATION has property with name "analyses" and value "true"
                        - id: SERVICE_PORTFOLIO_METHODOLOGY
                          is: Element
                          ofType: Business Object
                          where:
                            queryType: statement
                            query: $SERVICE_PORTFOLIO_METHODOLOGY has name "Service Portfolio Methodology"
                - id: value2
                  selector:
                    id: ALL_APPLICATION_SERVICES
                    is: Element
                    ofType: Application Service
            interpret:
              measure: "%"
              good:
                - value: "0.8"
                  relation: ">="
              normal:
                - relation: ">="
                  value: "0.6"
                - relation: "<"
                  value: "0.8"
              bad:
                - relation: "<"
                  value: "0.6"
    dependsOn:
      - alias: mergedModel
        ref: p://this/transformations/mergeModels/mergedModel




qualityGates:
  - strategy: auto
    policies:
      - name: VerifyArtifactExistence
        interpretation: threshold-
        actualValue: numberOfArtifacts
        setPoint: 3
        assessmentRef: p://this/assessments/artifactVerification

      - name: VerifySyntax
        interpretation: threshold-
        actualValue: isValid
        setPoint: 0.5
        assessmentRef: p://this/assessments/syntaxCheckAssessment

      - name: VerifyConsistency
        interpretation: threshold-
        actualValue: isValid
        setPoint: 0.5
        assessmentRef: p://this/assessments/consistencyCheckAssessment

      - name: VerifyBadMetrics
        interpretation: threshold+
        actualValue: numberOfBadKpis
        setPoint: 0.1
        assessmentRef: p://this/assessments/calculateKpis

      - name: VerifyArtifactExistence
        interpretation: threshold-
        actualValue: numberOfArtifacts
        setPoint: 3
        assessmentRef: p://this/assessments/artifactVerification

      - name: VerifyMergedSyntax
        interpretation: threshold-
        actualValue: isValid
        setPoint: 0.5
        assessmentRef: p://this/assessments/mergedSyntaxCheckAssessment

      - name: VerifyMergedConsistency
        interpretation: threshold-
        actualValue: isValid
        setPoint: 0.5
        assessmentRef: p://this/assessments/mergedConsistencyCheckAssessment

      - name: VerifyMergedBadMetrics
        interpretation: threshold+
        actualValue: numberOfBadKpis
        setPoint: 0.1
        assessmentRef: p://this/assessments/mergedCalculateKpis

  #    - name: VerifyAverageMetrics
  #      interpretation: threshold-
  #      actualValue: numberOfAverageKpis
  #      setPoint: 5
  #      assessmentRef: p://this/assessments/calculateKpis
#
  #    - name: VerifyGoodMetrics
  #      interpretation: threshold-
  #      actualValue: numberOfGoodKpis
  #      setPoint: 10
  #      assessmentRef: p://this/assessments/calculateKpis
