stages:
  - name: prepareModelData
    transformations:
      - checkoutCentralModel

transformations:
  - name: checkoutCentralModel
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/gitflow-test
      branch: release
