stages:
  - name: prepareModelData
    transformations:
      - checkoutCentralModel
      - checkoutProjectDeviantModel
      - checkoutConfigData
      - alignModelData
      - computeChangeSet
  - name: testAndAssess
    transformations:
      - testAndAssessCheckout
  - name: evolve
    transformations:
      - mergeModels
      - mergeGraphics

transformations:
  - name: checkoutCentralModel
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/gitflow-test
      branch: release

  - name: checkoutConfigData
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/config-repo
      branch: master

  - name: checkoutProjectDeviantModel
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/gitflow-test/
      branch: develop

  - name: commitAndPush
    service: git-service
    command: commitAndPush
    parameters:
      artifactId: "@mergedModel"
      approvalsReport: "@approvalsReport"
      repositoryUri: https://github.com/asab-se/gitflow-test
      branch: release
      credentials:
        type: plain
        username: eapipeline-user
        password: c66132e56c61cf8c8c2d91e5
    dependsOn:
      - alias: mergedModel
        ref: p://this/transformations/mergeModels/mergedModel
      - alias: approvalsReport
        ref: p://this/assessments/assessApprovals/approvalsReport



  - name: alignModelData
    service: ea-model-evolution-service
    command: alignModelData
    parameters:
      projectDeviantArtifactId: "@projectDeviant"
      threshold: "5"
    dependsOn:
      - alias: projectDeviant
        ref: p://this/transformations/checkoutProjectDeviantModel/workspace

  - name: computeChangeSet
    service: ea-model-evolution-service
    command: computeChangeSet
    parameters:
      centralModel: "@central"
      alignedModel: "@aligned"
    dependsOn:
      - alias: central
        ref: p://this/transformations/checkoutCentralModel/workspace
      - alias: aligned
        ref: p://this/transformations/alignModelData/alignModelArtifactId

  - name: testAndAssessCheckout
    service: ea-model-evolution-service
    command: testAndAssessCheckout
    parameters:
      changeSet: "@changeSet"
    dependsOn:
      - alias: changeSet
        ref: p://this/assessments/artifactVerification/changeSet

  - name: mergeModels
    service: ea-model-evolution-service
    command: mergeModels
    parameters:
      centralModel: "@centralModel"
      changeSet: "@changeSet"
      metricsReportArtifact: "@metricsReportArtifact"
    dependsOn:
      - alias: centralModel
        ref: p://this/transformations/checkoutCentralModel/workspace
      - alias: changeSet
        ref: p://this/assessments/artifactVerification/changeSet
      - alias: metricsReportArtifact
        ref: p://this/assessments/calculateKpis/metricsReportArtifact

  - name: mergeGraphics
    service: ea-model-evolution-service
    command: mergeGraphics
    parameters:
      mergedModel: "@mergedModel"
      projectModel: "@projectModel"
    dependsOn:
      - alias: mergedModel
        ref: p://this/transformations/mergeModels/mergedModel
      - alias: projectModel
        ref: p://this/transformations/checkoutProjectDeviantModel/workspace
