stages:
  - name: prepareModelData
    transformations:
      - checkoutCentralModel
      - checkoutProjectDeviation
      - alignModelData
      - computeChangeSet
      - artifactVerification
  - name: check model quality
    transformations:
      - consistencyCheck
      - syntaxCheck
      - badSmellsDetection

transformations:
  - name: checkoutCentralModel
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/centralEaRepository.git
      branch: master

  - name: checkoutProjectDeviation
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/projectEaRepository.git
      branch: master

  - name: alignModelData
    service: ea-model-evolution-service
    command: alignModelData
    parameters:
      projectDeviantArtifactId: "@artifact"
    dependsOn:
      - alias: artifact
        ref: p://this/transformations/checkoutProjectDeviation/projectModel

  - name: computeChangeSet
    service: ea-model-evolution-service
    command: computeChangeSet
    parameters:
      centralModel: "@centralArtifact"
      alignedModel: "@alignedArtifact"
    dependsOn:
      - alias: centralArtifact
        ref: p://this/transformations/checkoutCentralModel/centralModel
      - alias: alignedArtifact
        ref: p://this/transformations/alignModelData/alignedModel

assessments:
  - name: artifactVerification
    service: ea-model-evolution-service
    command: artifactVerificationAssessment
    parameters:
      centralModel: "@centralArtifact"
      alignedModel: "@alignedArtifact"
      changeSet: "@changeSetArtifact"
    dependsOn:
      - alias: centralArtifact
        ref: p://this/transformations/checkoutCentralModel/workspace
      - alias: alignedArtifact
        ref: p://this/transformations/alignModelData/alignedModelArtifactId
      - alias: changeSetArtifact
        ref: p://this/transformations/computeChangeSet/changeSetArtifactId

qualityGates:
  - strategy: auto
    policies:
      - name: ArtifactsValid
        interpretation: threshold-
        actualValue: numberOfArtifacts
        setPoint: 2.1
        assessmentRef: p://this/assessments/artifactVerification
