stages:
  - name: prepareModelData
    transformations:
      - checkoutProjectDeviation

transformations:
  - name: checkoutProjectDeviation
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/asab-se/projectEaRepository
      branch: master

assessments:
  - name: syntaxCheck
    service: ea-model-evolution-service
    command: syntaxCheckAssessment
    parameters:
      changeSet: "@repo"
      projectDeviantArtifactId: "@repo"
    dependsOn:
      - alias: repo
        ref: p://this/transformations/checkoutProjectDeviation/workspace

qualityGates:
  - strategy: auto
    policies:
      - name: SyntaxValidation
        interpretation: threshold+
        actualValue: isValid
        setPoint: 0.5
        assessmentRef: p://this/assessments/syntaxCheck
